### ISSUE TITLE
EventReactor.pm not found

### ISSUE THREAD

**Issue by leegee** [vti/reanimator#3]
What is EventReactor.pm? It doesn't appear to be on CPAN, or in the Makefile.PL, but the module appears to require it.

TIA
Lee

**Comment by luc2** [comment]
it's there :

https://github.com/vti/event_reactor

**Comment by leegee** [comment]
And referenced by modules on CPAN whilst not being on CPAN. Strange, and slightly upsetting,

Thanks, though.
